### ISSUE TITLE
[ERROR] failed to load locked problem! [0]

### ISSUE THREAD

**Issue by ttbian** [skygragon/leetcode-cli#124] opened 2018-10-10 16:51 UTC
I am able to login to leetcode and work on locked problems, is there anyway to show locked problem in command line tool? 
Thanks!

**Comment by sfdye** [comment] 2018-10-11 01:14
Duplicate of #91

Install from github mater will do the trick for now:

`npm i -g skygragon/leetcode-cli`

**Comment by skygragon** [comment] 2018-10-28 03:55
thanks @sfdye !

**Closed by skygragon** 2018-10-28 03:55 UTC
